### ISSUE TITLE
src attribute

### ISSUE THREAD

**Issue by evanbutera** [BrianDGLS/node-hologram#7]
When adding a src attribute to an external service (lorempixel et simila) in an example snippet, the module removes the // after http(s) 

i.e.
`      <img src="http://lorempixel.com/200/200">
`get parsed as 
     ` <img src="http:lorempixel.com/200/200">`

**Comment by BrianDGLS** [comment]
Could you paste in the entire doc as an example please?

I'm guessing this is a setting on the markdown converter.

**Comment by evanbutera** [comment]
`
/*doc

## Media item
<example>
    <div class="l-media">
      <div class="l-media__img">
        <img src="http:\/\/lorempixel.com/200/200">
      </div>
      <div class="l-media__bdy">
        body element
      </div>
    </div>
</example>


*/
`

escaping `//` resolves the problem 

`<img src="http://lorempixel.com/200/200">`  does not work,
`<img src="http\/\/:lorempixel.com/200/200">` no issues

I guess a documentation update will solve this problem.

**Comment by BrianDGLS** [comment]
This turned out to be a regex issue. The regex that was matching the comments also matched the `//` in the url and removed it.

The regex has been updated and the issue resolved on `develop`. This will require an update to the docs as the `/*doc */` comment that contains the markdown will now need to be the first comment in the file.

**Comment by evanbutera** [comment]
Seems good - also, forcing the documentation to be the first comment in the file will contribute to a much more organized code :)

**Comment by BrianDGLS** [comment]
Fixed in release 0.1.4:

https://www.npmjs.com/package/node-hologram
